* ✔DONE store username & password in some place that isn't the source code.
  CLOSED: [2021-03-29 Mon 02:52]
* ✔DONE log on(requires post request + cookies or something?), use colly framework?
  CLOSED: [2021-03-25 Thu 05:00]
* HOLD connect to and watch chat(?)
** ✔DONE detect "new match A vs B" notification, prompting a bet.
   CLOSED: [2021-03-25 Thu 05:00]
** ✔DONE REFACTOR move away from json polling model
   CLOSED: [2021-03-29 Mon 03:09]
*** The gamestate json status has info about open/closed/red won/blue won, but the window on win result is only a few seconds.
*** likely more efficient to watch chat or something.
*** TODO Create events for "new match", "match won", tournament start/end
* TODO query a database for data about players
* TODO calculate odds based on historical data, before match starts
* ✔DONE place bet
  CLOSED: [2021-03-29 Mon 02:00]
* ✔DONE calculate odds ratio of a match(calc'd from player totals)
  CLOSED: [2021-03-25 Thu 07:08]
*** TODO Store & use this data to rank competitors.
*** TODO [#C] BUG: Displays NaN:1 while bets are still open.
* INWK Detect game result
*** ✔DONE "websocket" connect to www.saltybet.com:2096
    CLOSED: [2021-03-29 Mon 01:59]
*** ✔DONE refresh json only on data recieved.
    CLOSED: [2021-03-29 Mon 01:59]
* TODO check/update balance when match is called.
*** #b, bal or balance is found in data[u]["b"], with data being the return of get("/zdata.json?t=" + ms) referenced/shown in updateData() of /j/www-cdn-jtvnw-x.js
*** TODO Fetch/update data accordingly.
* TODO I vaguely remember ?id= being in a url somewhere. id is the sid from the websocket. see ~line 200.
** ✔DONE wait for new match announcement
   CLOSED: [2021-03-29 Mon 02:03]
* support alternate game modes: tournament, exhibition based on Alert gamestate
** tournament balance is found in /ajax_tournament_start.php
** exhibition mode something or other is at /ajax_tournament_end.php
* what are values x, u, g, i, m and this other stuff?
** u, b(balance), g, i, m, are hidden inputs which may or may not be filled in after login.

* TODO [#A] BUG: client times out on state.json 
  2021/03/29 01:57:15 Get "https://www.saltybet.com/state.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  exit status 1
